In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('candyhierarchy2017.csv', encoding='latin-1')

In [3]:
df.head()

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers (a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,NaN,Raisins can go to hell,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"

In [4]:
df.shape

(2460, 120)

In [5]:
df.set_index('Internal ID', inplace = True)

In [6]:
df['Unnamed: 113'].value_counts(dropna = False)

NaN                                                                        2451
dress (https://survey.ubc.ca/media/assets/user/14372/storage/dress.png)       9
Name: Unnamed: 113, dtype: int64

In [7]:
## The columns 'Q5: STATE, PROVINCE, COUNTY, ETC', 'Q7: JOY OTHER', 'Q8: DESPAIR OTHER', 'Q9: OTHER COMMENTS', 'Unnamed: 113', and 'Click Coordinates (x, y)' have many missing values and are not useful, hence they will be dropped.
to_drop = ['Q5: STATE, PROVINCE, COUNTY, ETC', 'Q7: JOY OTHER', 'Q8: DESPAIR OTHER', 
           'Q9: OTHER COMMENTS', 'Unnamed: 113', 'Click Coordinates (x, y)']
df.drop(to_drop, inplace = True, axis = 1)

In [8]:
df.dtypes

Q1: GOING OUT?                                                                             object
Q2: GENDER                                                                                 object
Q3: AGE                                                                                    object
Q4: COUNTRY                                                                                object
Q6 | 100 Grand Bar                                                                         object
Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)     object
Q6 | Any full-sized candy bar                                                              object
Q6 | Black Jacks                                                                           object
Q6 | Bonkers (the candy)                                                                   object
Q6 | Bonkers (the board game)                                                              object
Q6 | Bottle Caps                                                                           object
Q6 | Box'o'Raisins                                                                         object
Q6 | Broken glow stick                                                                     object
Q6 | Butterfinger                                                                          object
Q6 | Cadbury Creme Eggs                                                                    object
Q6 | Candy Corn                                                                            object
Q6 | Candy that is clearly just the stuff given out for free at restaurants                object
Q6 | Caramellos                                                                            object
Q6 | Cash, or other forms of legal tender                                                  object
Q6 | Chardonnay                                                                            object
Q6 | Chick-o-Sticks (we donÃ•t know what that is)                                           object
Q6 | Chiclets                                                                              object
Q6 | Coffee Crisp                                                                          object
Q6 | Creepy Religious comics/Chick Tracts                                                  object
Q6 | Dental paraphenalia                                                                   object
Q6 | Dots                                                                                  object
Q6 | Dove Bars                                                                             object
Q6 | Fuzzy Peaches                                                                         object
Q6 | Generic Brand Acetaminophen                                                           object
Q6 | Glow sticks                                                                           object
                                                                                           ...
Q6 | Sandwich-sized bags filled with BooBerry Crunch                                       object
Q6 | Skittles                                                                              object
Q6 | Smarties (American)                                                                   object
Q6 | Smarties (Commonwealth)                                                               object
Q6 | Snickers                                                                              object
Q6 | Sourpatch Kids (i.e. abominations of nature)                                          object
Q6 | Spotted Dick                                                                          object
Q6 | Starburst                                                                             object
Q6 | Sweet Tarts                                                                           object
Q6 | Swedish Fish                                                                          object
Q6 | Sweetums (a friend to diabetes)                                                       object
Q6 | Take 5                                                                                object
Q6 | Tic Tacs                                                                              object
Q6 | Those odd marshmallow circus peanut things                                            object
Q6 | Three Musketeers                                                                      object
Q6 | Tolberone something or other                                                          object
Q6 | Trail Mix                                                                             object
Q6 | Twix                                                                                  object
Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein                object
Q6 | Vicodin                                                                               object
Q6 | Whatchamacallit Bars                                                                  object
Q6 | White Bread                                                                           object
Q6 | Whole Wheat anything                                                                  object
Q6 | York Peppermint Patties                                                               object
Q10: DRESS                                                                                 object
Q11: DAY                                                                                   object
Q12: MEDIA [Daily Dish]                                                                   float64
Q12: MEDIA [Science]                                                                      float64
Q12: MEDIA [ESPN]                                                                         float64
Q12: MEDIA [Yahoo]                                                                        float64
Length: 113, dtype: object

In [9]:
for col in df:
    if df[col].dtypes == 'float64':
        df[col] = df[col].fillna('0')

In [10]:
df.head()

,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers (a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),Q6 | Bonkers (the board game),...,Q6 | Whatchamacallit Bars,Q6 | White Bread,Q6 | Whole Wheat anything,Q6 | York Peppermint Patties,Q10: DRESS,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo]
Internal ID,,,,,,,,,,,,,,,,,,,,,
90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
90272821,No,Male,44,USA,MEH,DESPAIR,JOY,MEH,DESPAIR,DESPAIR,...,DESPAIR,DESPAIR,DESPAIR,DESPAIR,White and gold,Sunday,0,1,0,0
90272829,NaN,Male,49,USA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
90272840,No,Male,40,us,MEH,DESPAIR,JOY,MEH,MEH,DESPAIR,...,JOY,DESPAIR,DESPAIR,DESPAIR,White and gold,Sunday,0,1,0,0
90272841,No,Male,23,usa,JOY,DESPAIR,JOY,DESPAIR,MEH,DESPAIR,...,JOY,DESPAIR,DESPAIR,JOY,White and gold,Friday,0,1,0,0

In [11]:
candies = df.iloc[:, 6:-10]
candies.describe()

,Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),Q6 | Bonkers (the board game),Q6 | Bottle Caps,Q6 | Box'o'Raisins,Q6 | Broken glow stick,Q6 | Butterfinger,Q6 | Cadbury Creme Eggs,Q6 | Candy Corn,...,Q6 | Sweetums (a friend to diabetes),Q6 | Take 5,Q6 | Tic Tacs,Q6 | Those odd marshmallow circus peanut things,Q6 | Three Musketeers,Q6 | Tolberone something or other,Q6 | Trail Mix,Q6 | Twix,"Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein",Q6 | Vicodin
count,1788,1502,1468,1454,1695,1772,1754,1778,1777,1782,...,1458,1543,1746,1724,1752,1754,1752,1770,1668,1671
unique,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
top,JOY,DESPAIR,MEH,MEH,MEH,DESPAIR,DESPAIR,JOY,JOY,DESPAIR,...,DESPAIR,MEH,DESPAIR,DESPAIR,JOY,JOY,DESPAIR,JOY,DESPAIR,DESPAIR
freq,1559,793,857,715,670,1179,1625,1177,820,743,...,763,613,754,1252,1058,1320,836,1413,1146,723

In [12]:
df['Q4: COUNTRY'].unique()

array([nan, 'USA ', 'USA', 'us', 'usa', 'canada', 'Canada', 'Us', 'US',
       'Murica', 'United States', 'uk', 'United Kingdom', 'united states',
       'Usa', 'United States ', 'United staes',
       'United States of America', 'UAE', 'England', 'UK', 'canada ',
       'Mexico', 'United states', 'u.s.a.', 'USAUSAUSA', 'america', '35',
       'france', 'United States of America ', 'U.S.A.', 'finland',
       'unhinged states', 'Canada ', 'united states of america',
       'US of A', 'Unites States', 'The United States', 'North Carolina ',
       'Unied States', 'Netherlands', 'germany', 'Europe', 'Earth', 'U S',
       'u.s.', 'U.K. ', 'Costa Rica', 'The United States of America',
       'unite states', 'U.S.', '46', 'cascadia', 'Australia',
       'insanity lately', 'Greece', 'USA? Hard to tell anymore..',
       "'merica", 'usas', 'Pittsburgh', '45', 'United State', '32',
       'France', 'australia', 'A', 'Can', 'Canae', 'New York',
       'Trumpistan', 'Ireland', 'United Sates', 'Korea', 'California',
       'Japan', 'USa', 'South africa',
       'I pretend to be from Canada, but I am really from the United States.',
       'Usa ', 'Uk', 'Iceland', 'Germany', 'Canada`', 'Scotland', 'UK ',
       'Denmark', 'United Stated', 'France ', 'Switzerland',
       'Ahem....Amerca', 'UD', 'Scotland ', 'South Korea', 'New Jersey',
       'CANADA', 'Indonesia', 'United ststes', 'America',
       'The Netherlands', 'United Statss', 'endland', 'Atlantis',
       'murrika', 'USA! USA! USA!', 'USAA', 'Alaska', 'united States ',
       'soviet canuckistan', 'N. America', 'Singapore', 'USSA', 'China',
       'Taiwan', 'Ireland ', 'hong kong', 'spain', 'Sweden', 'Hong Kong',
       'U.S. ', 'Narnia', 'u s a', 'United Statea', 'united ststes', '1',
       'subscribe to dm4uz3 on youtube', 'United kingdom',
       'USA USA USA!!!!', "I don't know anymore", 'Fear and Loathing'],
      dtype=object)

In [13]:
df.replace(['murrika', 'Murica', 'A', 'USAA', 'USA ', 'us', 'USA', 'US', 'Us', 'usa', 'united states', 
            'united states of america', 'Usa', 'United States ', 'United staes','United States of America',
            'United states','u.s.a.','USAUSAUSA', 'america', 'United States of America ','U.S.A.', 'unhinged states',
            'united states of america', 'US of A', 'Unites States', 'The United States', 'North Carolina ','Unied States',
            'U S', 'u.s.', 'The United States of America', 'unite states', 'U.S.', 'cascadia', 'USA? Hard to tell anymore..', "'merica", 'usas', 'Pittsburgh', 
            'United State', 'New York', 'Trumpistan', 'United Sates', 'California', 'USa',
            'I pretend to be from Canada, but I am really from the United States.', 'Usa ', 'United Stated',
            'Ahem....Amerca', 'UD', 'New Jersey', 'United ststes', 'America', 'United Statss', 'USA! USA! USA!',
            'Alaska', 'united States ', 'N. America', 'USSA', 'U.S. ', 'u s a', 'United Statea', 'united ststes', 
            'USA USA USA!!!!'], "United States", inplace = True)
df.replace(['Soviet Canuckistan','Soviet canuckistan', 'canada', 'Canada', 'canada ', 'Canada ', 'Can', 'Canae', 'Canada`',
            'CANADA'], "Canada", inplace = True)
df.replace(['United kingdom', 'uk', 'United Kingdom', 'UK', 'U.K. ', 'Uk', 'UK ', 'Scotland ', 'England'], "United Kingdom",
           inplace = True)
df.replace(['finland'], 'Finland', inplace = True)
df.replace(['france', 'France', 'France '], 'France', inplace = True)
df.replace(['The Netherlands', 'Netherlands'], 'Netherlands', inplace = True)
df.replace(['Ireland ', 'Ireland'], 'Ireland', inplace = True)
df.replace(['Uae'], 'United Arab Emirates', inplace = True)
df.replace(['35', 'Europe', 'Earth', '46', 'insanity lately', '45', '32', 'endland', 'Atlantis', 'Narnia', '1', 
            'subscribe to dm4uz3 on youtube',  "I don't know anymore", 'Fear and Loathing'], np.nan, inplace = True)
df['Q4: COUNTRY'] = df['Q4: COUNTRY'].str.title()

In [14]:
df['Q4: COUNTRY'].unique()

array([nan, 'United States', 'Canada', 'United Kingdom', 'Uae', 'Mexico',
       'France', 'Finland', 'Netherlands', 'Germany', 'Costa Rica',
       'Australia', 'Greece', 'Ireland', 'Korea', 'Japan', 'South Africa',
       'Iceland', 'Scotland', 'Denmark', 'Switzerland', 'South Korea',
       'Indonesia', 'Soviet Canuckistan', 'Singapore', 'China', 'Taiwan',
       'Hong Kong', 'Spain', 'Sweden'], dtype=object)

In [15]:
df['Q2: GENDER'].unique()

array([nan, 'Male', 'Female', "I'd rather not say", 'Other'], dtype=object)

In [16]:
df.replace(["I'd rather not say", 'Other'], np.nan, inplace = True)

In [17]:
df['Q3: AGE'].unique()

array([nan, '44', '49', '40', '23', '53', '33', '43', '56', '64', '37',
       '59', '48', '54', '36', '25', '34', '38', '58', '50', '47', '16',
       '52', '63', '65', '41', '27', '31', '61', '42', '62', '29', '39',
       '28', '69', '67', '30', '22', '26', '51', '70', '24', '18', '19',
       'Old enough', '57', '60', '66', '12', 'Many', '55', '72', '?',
       '21', '11', 'no', '9', '68', '20', '6', '10', '71', '90', '13',
       '45-55', '312', '99', '7', 'hahahahaha', '88', '39.4', '74', '102',
       'older than dirt', '17', '15', '8', '75', '5u', 'Enough',
       'See question 2', '24-50', '14', 'Over 50', '100', '76', '1000',
       'sixty-nine', '46 Halloweens.', 'ancient', '77', 'OLD', 'old',
       '73', '70 1/2', 'MY NAME JEFF', '4',
       '59 on the day after Halloween', 'old enough', 'your mom',
       'I can remember when Java was a cool new language', '60+'],
      dtype=object)

In [18]:
# Unexpected missing values will be removed.
df['Q3: AGE'] = df['Q3: AGE'].apply(pd.to_numeric, errors = 'coerce')

In [19]:
df['Q3: AGE'].unique()

array([   nan,   44. ,   49. ,   40. ,   23. ,   53. ,   33. ,   43. ,
         56. ,   64. ,   37. ,   59. ,   48. ,   54. ,   36. ,   25. ,
         34. ,   38. ,   58. ,   50. ,   47. ,   16. ,   52. ,   63. ,
         65. ,   41. ,   27. ,   31. ,   61. ,   42. ,   62. ,   29. ,
         39. ,   28. ,   69. ,   67. ,   30. ,   22. ,   26. ,   51. ,
         70. ,   24. ,   18. ,   19. ,   57. ,   60. ,   66. ,   12. ,
         55. ,   72. ,   21. ,   11. ,    9. ,   68. ,   20. ,    6. ,
         10. ,   71. ,   90. ,   13. ,  312. ,   99. ,    7. ,   88. ,
         39.4,   74. ,  102. ,   17. ,   15. ,    8. ,   75. ,   14. ,
        100. ,   76. , 1000. ,   77. ,   73. ,    4. ])

In [20]:
df.head()

,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers (a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),Q6 | Bonkers (the board game),...,Q6 | Whatchamacallit Bars,Q6 | White Bread,Q6 | Whole Wheat anything,Q6 | York Peppermint Patties,Q10: DRESS,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo]
Internal ID,,,,,,,,,,,,,,,,,,,,,
90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
90272821,No,Male,44.0,United States,MEH,DESPAIR,JOY,MEH,DESPAIR,DESPAIR,...,DESPAIR,DESPAIR,DESPAIR,DESPAIR,White and gold,Sunday,0,1,0,0
90272829,NaN,Male,49.0,United States,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
90272840,No,Male,40.0,United States,MEH,DESPAIR,JOY,MEH,MEH,DESPAIR,...,JOY,DESPAIR,DESPAIR,DESPAIR,White and gold,Sunday,0,1,0,0
90272841,No,Male,23.0,United States,JOY,DESPAIR,JOY,DESPAIR,MEH,DESPAIR,...,JOY,DESPAIR,DESPAIR,JOY,White and gold,Friday,0,1,0,0